const data = [
  {
    id: 1,
    Description: "risus praesent lectus",
    Category: "Machines",
    SubCategory: "heavy hex",
    Type: "ut",
    Specification: "sit amet turpis",
    Material: "Diamond",
    Quantity: 21,
    PurchaseDate: "8/10/2018"
  },
  {
    id: 2,
    Description: "tortor",
    Category: "measuring instrument",
    SubCategory: "hammers",
    Type: "velit",
    Specification: "nibh in hac",
    Material: "Cemented carbides",
    Quantity: 98,
    PurchaseDate: "1/29/2019"
  },
  {
    id: 3,
    Description: "in lacus",
    Category: "measuring instrument",
    SubCategory: "hammers",
    Type: "pede",
    Specification: "diam vitae quam",
    Material: "Cermets",
    Quantity: 91,
    PurchaseDate: "4/6/2019"
  },
  {
    id: 4,
    Description: "maecenas tristique est",
    Category: "measuring instrument",
    SubCategory: "machine screws",
    Type: "id",
    Specification: "libero quis orci",
    Material: "CBN",
    Quantity: 79,
    PurchaseDate: "12/27/2018"
  },
  {
    id: 5,
    Description: "ut massa volutpat convallis",
    Category: "Tools",
    SubCategory: "files",
    Type: "sociis",
    Specification: "aenean sit amet",
    Material: "Cemented carbides",
    Quantity: 43,
    PurchaseDate: "8/16/2018"
  },
  {
    id: 6,
    Description: "interdum eu",
    Category: "Machines",
    SubCategory: "flat",
    Type: "in",
    Specification: "sit",
    Material: "CBN",
    Quantity: 28,
    PurchaseDate: "7/29/2018"
  },
  {
    id: 7,
    Description: "dictumst aliquam augue quam",
    Category: "Fluids",
    SubCategory: "brushes",
    Type: "sagittis",
    Specification: "eget",
    Material: "Cemented carbides",
    Quantity: 56,
    PurchaseDate: "2/10/2019"
  },
  {
    id: 8,
    Description: "lacus",
    Category: "Tools",
    SubCategory: "Vacuum Cleaner",
    Type: "aenean",
    Specification: "ut",
    Material: "Cemented carbides",
    Quantity: 99,
    PurchaseDate: "8/11/2018"
  },
  {
    id: 9,
    Description: "donec",
    Category: "Tools",
    SubCategory: "lubrication",
    Type: "mollis",
    Specification: "nulla",
    Material: "Cermets",
    Quantity: 42,
    PurchaseDate: "1/8/2019"
  },
  {
    id: 10,
    Description: "enim leo rhoncus",
    Category: "Tools",
    SubCategory: "oil stones",
    Type: "fringilla",
    Specification: "nullam",
    Material: "Cermets",
    Quantity: 64,
    PurchaseDate: "10/30/2018"
  },
  {
    id: 11,
    Description: "mauris enim leo",
    Category: "Machines",
    SubCategory: "oil stones",
    Type: "magna",
    Specification: "vulputate",
    Material: "Sialon",
    Quantity: 91,
    PurchaseDate: "3/11/2019"
  },
  {
    id: 12,
    Description: "ultrices aliquet maecenas",
    Category: "Machines",
    SubCategory: "Hex",
    Type: "et",
    Specification: "mauris",
    Material: "Diamond",
    Quantity: 23,
    PurchaseDate: "4/15/2019"
  },
  {
    id: 13,
    Description: "adipiscing elit",
    Category: "Fluids",
    SubCategory: "heavy hex",
    Type: "risus",
    Specification: "augue vel accumsan",
    Material: "HCS",
    Quantity: 16,
    PurchaseDate: "9/21/2018"
  },
  {
    id: 14,
    Description: "maecenas pulvinar lobortis",
    Category: "Fastners",
    SubCategory: "cutting oil",
    Type: "vestibulum",
    Specification: "lacus",
    Material: "Cemented carbides",
    Quantity: 82,
    PurchaseDate: "8/28/2018"
  },
  {
    id: 15,
    Description: "elit sodales scelerisque mauris",
    Category: "Machines",
    SubCategory: "hammers",
    Type: "velit",
    Specification: "nullam",
    Material: "HCS",
    Quantity: 92,
    PurchaseDate: "5/16/2018"
  },
  {
    id: 16,
    Description: "at vulputate",
    Category: "Fluids",
    SubCategory: "compass",
    Type: "metus",
    Specification: "pretium iaculis diam",
    Material: "HSS",
    Quantity: 73,
    PurchaseDate: "2/5/2019"
  },
  {
    id: 17,
    Description: "eros viverra",
    Category: "Tools",
    SubCategory: "vernier",
    Type: "id",
    Specification: "phasellus id sapien",
    Material: "HCS",
    Quantity: 83,
    PurchaseDate: "8/17/2018"
  },
  {
    id: 18,
    Description: "in felis eu sapien",
    Category: "Machines",
    SubCategory: "wood screws",
    Type: "sed",
    Specification: "suspendisse accumsan",
    Material: "UCON",
    Quantity: 40,
    PurchaseDate: "12/26/2018"
  },
  {
    id: 19,
    Description: "neque aenean auctor",
    Category: "Tools",
    SubCategory: "allenkeys",
    Type: "tempor",
    Specification: "platea dictumst morbi",
    Material: "HSS",
    Quantity: 7,
    PurchaseDate: "5/22/2018"
  },
  {
    id: 20,
    Description: "mattis pulvinar nulla",
    Category: "Fluids",
    SubCategory: "revet nut tool",
    Type: "rutrum",
    Specification: "massa donec dapibus",
    Material: "Diamond",
    Quantity: 54,
    PurchaseDate: "5/17/2018"
  },
  {
    id: 21,
    Description: "nunc purus",
    Category: "Tools",
    SubCategory: "threadcutting tools",
    Type: "dolor",
    Specification: "aliquet ultrices",
    Material: "HCS",
    Quantity: 21,
    PurchaseDate: "10/16/2018"
  },
  {
    id: 22,
    Description: "metus arcu adipiscing",
    Category: "measuring instrument",
    SubCategory: "taps",
    Type: "morbi",
    Specification: "tristique",
    Material: "Diamond",
    Quantity: 99,
    PurchaseDate: "11/25/2018"
  },
  {
    id: 23,
    Description: "parturient montes",
    Category: "measuring instrument",
    SubCategory: "washers",
    Type: "velit",
    Specification: "ridiculus",
    Material: "Diamond",
    Quantity: 61,
    PurchaseDate: "5/21/2018"
  },
  {
    id: 24,
    Description: "luctus cum sociis",
    Category: "Machines",
    SubCategory: "vernier",
    Type: "praesent",
    Specification: "morbi",
    Material: "Sialon",
    Quantity: 6,
    PurchaseDate: "1/7/2019"
  },
  {
    id: 25,
    Description: "aenean lectus",
    Category: "measuring instrument",
    SubCategory: "hammers",
    Type: "commodo",
    Specification: "iaculis diam",
    Material: "Cermets",
    Quantity: 27,
    PurchaseDate: "4/9/2019"
  },
  {
    id: 26,
    Description: "erat id mauris vulputate",
    Category: "Machines",
    SubCategory: "mill cutters",
    Type: "lacus",
    Specification: "libero non mattis",
    Material: "Cermets",
    Quantity: 7,
    PurchaseDate: "8/4/2018"
  },
  {
    id: 27,
    Description: "dui",
    Category: "Fastners",
    SubCategory: "hammers",
    Type: "dapibus",
    Specification: "donec diam neque",
    Material: "HSS",
    Quantity: 48,
    PurchaseDate: "11/13/2018"
  },
  {
    id: 28,
    Description: "sed tristique in tempus",
    Category: "Fluids",
    SubCategory: "Clamping tools",
    Type: "mi",
    Specification: "dolor",
    Material: "HCS",
    Quantity: 22,
    PurchaseDate: "3/15/2019"
  },
  {
    id: 29,
    Description: "turpis",
    Category: "Fluids",
    SubCategory: "revet nut tool",
    Type: "tincidunt",
    Specification: "eu",
    Material: "Cemented carbides",
    Quantity: 67,
    PurchaseDate: "1/4/2019"
  },
  {
    id: 30,
    Description: "a ipsum",
    Category: "Fluids",
    SubCategory: "revet nut tool",
    Type: "risus",
    Specification: "est quam",
    Material: "CBN",
    Quantity: 59,
    PurchaseDate: "8/6/2018"
  },
  {
    id: 31,
    Description: "rhoncus sed vestibulum",
    Category: "measuring instrument",
    SubCategory: "lathe tools",
    Type: "ut",
    Specification: "nisi",
    Material: "UCON",
    Quantity: 78,
    PurchaseDate: "2/13/2019"
  },
  {
    id: 32,
    Description: "velit",
    Category: "Fluids",
    SubCategory: "Rugs",
    Type: "luctus",
    Specification: "vivamus",
    Material: "HSS",
    Quantity: 3,
    PurchaseDate: "1/29/2019"
  },
  {
    id: 33,
    Description: "neque sapien placerat ante",
    Category: "Machines",
    SubCategory: "bolts",
    Type: "nisi",
    Specification: "tincidunt in leo",
    Material: "Cermets",
    Quantity: 9,
    PurchaseDate: "9/28/2018"
  },
  {
    id: 34,
    Description: "vitae consectetuer eget",
    Category: "Fluids",
    SubCategory: "cutting oil",
    Type: "nunc",
    Specification: "massa tempor convallis",
    Material: "CBN",
    Quantity: 57,
    PurchaseDate: "10/4/2018"
  },
  {
    id: 35,
    Description: "primis",
    Category: "Fastners",
    SubCategory: "Hex",
    Type: "in",
    Specification: "interdum mauris",
    Material: "Diamond",
    Quantity: 17,
    PurchaseDate: "10/27/2018"
  },
  {
    id: 36,
    Description: "vel est donec odio",
    Category: "Machines",
    SubCategory: "fender",
    Type: "orci",
    Specification: "nisl nunc nisl",
    Material: "Diamond",
    Quantity: 83,
    PurchaseDate: "6/6/2018"
  },
  {
    id: 37,
    Description: "in",
    Category: "Fluids",
    SubCategory: "washers",
    Type: "adipiscing",
    Specification: "duis",
    Material: "HCS",
    Quantity: 66,
    PurchaseDate: "3/28/2019"
  },
  {
    id: 38,
    Description: "mi",
    Category: "Fastners",
    SubCategory: "Vacuum Cleaner",
    Type: "habitasse",
    Specification: "justo",
    Material: "HCS",
    Quantity: 61,
    PurchaseDate: "10/25/2018"
  },
  {
    id: 39,
    Description: "platea dictumst",
    Category: "Fastners",
    SubCategory: "hammers",
    Type: "quis",
    Specification: "convallis nunc proin",
    Material: "Cermets",
    Quantity: 10,
    PurchaseDate: "11/22/2018"
  },
  {
    id: 40,
    Description: "maecenas rhoncus aliquam",
    Category: "measuring instrument",
    SubCategory: "hacksaw",
    Type: "neque",
    Specification: "duis faucibus accumsan",
    Material: "HSS",
    Quantity: 45,
    PurchaseDate: "10/22/2018"
  },
  {
    id: 41,
    Description: "justo",
    Category: "measuring instrument",
    SubCategory: "screws",
    Type: "quam",
    Specification: "vivamus vestibulum sagittis",
    Material: "Cemented carbides",
    Quantity: 75,
    PurchaseDate: "7/14/2018"
  },
  {
    id: 42,
    Description: "blandit",
    Category: "Fastners",
    SubCategory: "hacksaw",
    Type: "nibh",
    Specification: "elementum",
    Material: "Diamond",
    Quantity: 7,
    PurchaseDate: "10/27/2018"
  },
  {
    id: 43,
    Description: "turpis sed",
    Category: "Fluids",
    SubCategory: "spanners",
    Type: "ut",
    Specification: "suspendisse",
    Material: "Diamond",
    Quantity: 12,
    PurchaseDate: "12/22/2018"
  },
  {
    id: 44,
    Description: "donec",
    Category: "Fluids",
    SubCategory: "safety equipments",
    Type: "tortor",
    Specification: "accumsan",
    Material: "Sialon",
    Quantity: 31,
    PurchaseDate: "5/24/2018"
  },
  {
    id: 45,
    Description: "id luctus nec molestie",
    Category: "measuring instrument",
    SubCategory: "goggles",
    Type: "enim",
    Specification: "imperdiet",
    Material: "Cermets",
    Quantity: 4,
    PurchaseDate: "6/22/2018"
  },
  {
    id: 46,
    Description: "posuere metus",
    Category: "measuring instrument",
    SubCategory: "goggles",
    Type: "in",
    Specification: "nullam molestie",
    Material: "Sialon",
    Quantity: 18,
    PurchaseDate: "3/19/2019"
  },
  {
    id: 47,
    Description: "purus eu magna",
    Category: "Tools",
    SubCategory: "bar clamps",
    Type: "sit",
    Specification: "quam pede lobortis",
    Material: "HSS",
    Quantity: 16,
    PurchaseDate: "8/10/2018"
  },
  {
    id: 48,
    Description: "pede",
    Category: "Machines",
    SubCategory: "drill",
    Type: "bibendum",
    Specification: "nunc vestibulum ante",
    Material: "CBN",
    Quantity: 9,
    PurchaseDate: "7/30/2018"
  },
  {
    id: 49,
    Description: "turpis elementum ligula",
    Category: "Fluids",
    SubCategory: "wood screws",
    Type: "mattis",
    Specification: "viverra diam",
    Material: "Cemented carbides",
    Quantity: 12,
    PurchaseDate: "2/25/2019"
  },
  {
    id: 50,
    Description: "convallis tortor risus",
    Category: "Tools",
    SubCategory: "Hex",
    Type: "vivamus",
    Specification: "magna",
    Material: "Cemented carbides",
    Quantity: 98,
    PurchaseDate: "3/5/2019"
  },
  {
    id: 51,
    Description: "turpis adipiscing",
    Category: "Tools",
    SubCategory: "t bolts",
    Type: "sociis",
    Specification: "luctus",
    Material: "UCON",
    Quantity: 55,
    PurchaseDate: "9/7/2018"
  },
  {
    id: 52,
    Description: "cubilia curae mauris viverra",
    Category: "Tools",
    SubCategory: "threadcutting tools",
    Type: "tincidunt",
    Specification: "gravida sem",
    Material: "CBN",
    Quantity: 100,
    PurchaseDate: "8/19/2018"
  },
  {
    id: 53,
    Description: "quisque porta",
    Category: "Tools",
    SubCategory: "hammers",
    Type: "id",
    Specification: "lorem ipsum",
    Material: "Cermets",
    Quantity: 3,
    PurchaseDate: "1/21/2019"
  },
  {
    id: 54,
    Description: "orci",
    Category: "Fluids",
    SubCategory: "Rugs",
    Type: "vel",
    Specification: "nulla",
    Material: "HSS",
    Quantity: 2,
    PurchaseDate: "6/17/2018"
  },
  {
    id: 55,
    Description: "platea",
    Category: "Fluids",
    SubCategory: "Glue guns",
    Type: "mi",
    Specification: "mi",
    Material: "Cermets",
    Quantity: 20,
    PurchaseDate: "10/7/2018"
  },
  {
    id: 56,
    Description: "donec ut dolor",
    Category: "Fluids",
    SubCategory: "nuts",
    Type: "ultrices",
    Specification: "phasellus",
    Material: "Diamond",
    Quantity: 34,
    PurchaseDate: "6/1/2018"
  },
  {
    id: 57,
    Description: "consectetuer",
    Category: "Machines",
    SubCategory: "spirit level",
    Type: "ligula",
    Specification: "justo pellentesque viverra",
    Material: "Sialon",
    Quantity: 41,
    PurchaseDate: "2/26/2019"
  },
  {
    id: 58,
    Description: "consectetuer",
    Category: "Fastners",
    SubCategory: "callipers",
    Type: "consectetuer",
    Specification: "elit proin",
    Material: "Cemented carbides",
    Quantity: 27,
    PurchaseDate: "10/18/2018"
  },
  {
    id: 59,
    Description: "lacinia sapien quis",
    Category: "Tools",
    SubCategory: "goggles",
    Type: "ac",
    Specification: "eu",
    Material: "HCS",
    Quantity: 88,
    PurchaseDate: "1/14/2019"
  },
  {
    id: 60,
    Description: "ante vivamus",
    Category: "Fastners",
    SubCategory: "goggles",
    Type: "est",
    Specification: "luctus et",
    Material: "Diamond",
    Quantity: 82,
    PurchaseDate: "6/15/2018"
  },
  {
    id: 61,
    Description: "odio",
    Category: "Tools",
    SubCategory: "punch",
    Type: "lectus",
    Specification: "eu",
    Material: "Cemented carbides",
    Quantity: 35,
    PurchaseDate: "6/6/2018"
  },
  {
    id: 62,
    Description: "donec quis",
    Category: "measuring instrument",
    SubCategory: "spanners",
    Type: "ligula",
    Specification: "in",
    Material: "HSS",
    Quantity: 50,
    PurchaseDate: "1/27/2019"
  },
  {
    id: 63,
    Description: "diam nam",
    Category: "Fastners",
    SubCategory: "parallel blocks",
    Type: "convallis",
    Specification: "morbi vel lectus",
    Material: "Cemented carbides",
    Quantity: 48,
    PurchaseDate: "3/10/2019"
  },
  {
    id: 64,
    Description: "in",
    Category: "measuring instrument",
    SubCategory: "flat",
    Type: "lobortis",
    Specification: "rutrum nulla nunc",
    Material: "Diamond",
    Quantity: 30,
    PurchaseDate: "12/26/2018"
  },
  {
    id: 65,
    Description: "ac neque duis",
    Category: "Fluids",
    SubCategory: "center punches",
    Type: "suscipit",
    Specification: "rhoncus mauris enim",
    Material: "Sialon",
    Quantity: 55,
    PurchaseDate: "10/18/2018"
  },
  {
    id: 66,
    Description: "curae duis faucibus accumsan",
    Category: "Fastners",
    SubCategory: "Handtools",
    Type: "sem",
    Specification: "felis",
    Material: "HCS",
    Quantity: 51,
    PurchaseDate: "4/25/2018"
  },
  {
    id: 67,
    Description: "mauris enim",
    Category: "Fastners",
    SubCategory: "hammers",
    Type: "condimentum",
    Specification: "eros suspendisse",
    Material: "UCON",
    Quantity: 58,
    PurchaseDate: "6/28/2018"
  },
  {
    id: 68,
    Description: "vulputate luctus cum",
    Category: "Machines",
    SubCategory: "cleaning tools",
    Type: "sit",
    Specification: "velit nec",
    Material: "CBN",
    Quantity: 78,
    PurchaseDate: "5/4/2018"
  },
  {
    id: 69,
    Description: "vestibulum velit id",
    Category: "measuring instrument",
    SubCategory: "Glue guns",
    Type: "sit",
    Specification: "primis in faucibus",
    Material: "HCS",
    Quantity: 6,
    PurchaseDate: "4/14/2019"
  },
  {
    id: 70,
    Description: "porttitor",
    Category: "Machines",
    SubCategory: "bar clamps",
    Type: "sit",
    Specification: "dis",
    Material: "Sialon",
    Quantity: 18,
    PurchaseDate: "1/15/2019"
  },
  {
    id: 71,
    Description: "venenatis turpis",
    Category: "Fluids",
    SubCategory: "allenkeys",
    Type: "mauris",
    Specification: "luctus cum",
    Material: "UCON",
    Quantity: 25,
    PurchaseDate: "7/18/2018"
  },
  {
    id: 72,
    Description: "felis ut at",
    Category: "Fastners",
    SubCategory: "cutting tools",
    Type: "eros",
    Specification: "convallis",
    Material: "Cermets",
    Quantity: 70,
    PurchaseDate: "8/20/2018"
  },
  {
    id: 73,
    Description: "dui vel sem",
    Category: "Fastners",
    SubCategory: "step blocks",
    Type: "justo",
    Specification: "eu massa donec",
    Material: "Cemented carbides",
    Quantity: 53,
    PurchaseDate: "4/10/2019"
  },
  {
    id: 74,
    Description: "cubilia",
    Category: "measuring instrument",
    SubCategory: "drill",
    Type: "sed",
    Specification: "nunc proin at",
    Material: "CBN",
    Quantity: 79,
    PurchaseDate: "12/30/2018"
  },
  {
    id: 75,
    Description: "sed magna at",
    Category: "measuring instrument",
    SubCategory: "Glue guns",
    Type: "non",
    Specification: "justo nec condimentum",
    Material: "UCON",
    Quantity: 62,
    PurchaseDate: "7/31/2018"
  },
  {
    id: 76,
    Description: "ante vel ipsum",
    Category: "measuring instrument",
    SubCategory: "Vacuum Cleaner",
    Type: "congue",
    Specification: "eget tempus vel",
    Material: "Cermets",
    Quantity: 94,
    PurchaseDate: "6/23/2018"
  },
  {
    id: 77,
    Description: "iaculis congue vivamus metus",
    Category: "Tools",
    SubCategory: "tape",
    Type: "sit",
    Specification: "lacus at",
    Material: "HSS",
    Quantity: 80,
    PurchaseDate: "11/5/2018"
  },
  {
    id: 78,
    Description: "ornare consequat",
    Category: "Tools",
    SubCategory: "washers",
    Type: "sociis",
    Specification: "in",
    Material: "Diamond",
    Quantity: 62,
    PurchaseDate: "10/23/2018"
  },
  {
    id: 79,
    Description: "placerat praesent blandit nam",
    Category: "Machines",
    SubCategory: "vices",
    Type: "ut",
    Specification: "odio elementum",
    Material: "Cermets",
    Quantity: 75,
    PurchaseDate: "10/3/2018"
  },
  {
    id: 80,
    Description: "in libero",
    Category: "Fluids",
    SubCategory: "ear muffs",
    Type: "velit",
    Specification: "augue aliquam erat",
    Material: "Diamond",
    Quantity: 86,
    PurchaseDate: "4/5/2019"
  },
  {
    id: 81,
    Description: "felis",
    Category: "Fastners",
    SubCategory: "F clamps",
    Type: "accumsan",
    Specification: "vel augue",
    Material: "CBN",
    Quantity: 66,
    PurchaseDate: "10/6/2018"
  },
  {
    id: 82,
    Description: "turpis a pede posuere",
    Category: "Fastners",
    SubCategory: "Dustbins",
    Type: "cursus",
    Specification: "sem duis aliquam",
    Material: "UCON",
    Quantity: 86,
    PurchaseDate: "2/15/2019"
  },
  {
    id: 83,
    Description: "hac habitasse platea dictumst",
    Category: "Fluids",
    SubCategory: "hammers",
    Type: "maecenas",
    Specification: "faucibus orci",
    Material: "Sialon",
    Quantity: 52,
    PurchaseDate: "8/14/2018"
  },
  {
    id: 84,
    Description: "mus",
    Category: "Fluids",
    SubCategory: "files",
    Type: "ac",
    Specification: "odio odio elementum",
    Material: "UCON",
    Quantity: 83,
    PurchaseDate: "10/17/2018"
  },
  {
    id: 85,
    Description: "ultrices posuere cubilia",
    Category: "measuring instrument",
    SubCategory: "tape",
    Type: "rhoncus",
    Specification: "faucibus cursus urna",
    Material: "Diamond",
    Quantity: 92,
    PurchaseDate: "12/15/2018"
  },
  {
    id: 86,
    Description: "nulla sed accumsan",
    Category: "Fluids",
    SubCategory: "heavy hex",
    Type: "vestibulum",
    Specification: "felis",
    Material: "UCON",
    Quantity: 39,
    PurchaseDate: "1/25/2019"
  },
  {
    id: 87,
    Description: "consequat metus",
    Category: "Fastners",
    SubCategory: "pliers",
    Type: "ultrices",
    Specification: "id",
    Material: "Cemented carbides",
    Quantity: 70,
    PurchaseDate: "3/18/2019"
  },
  {
    id: 88,
    Description: "pulvinar",
    Category: "Fastners",
    SubCategory: "Hex",
    Type: "nunc",
    Specification: "nullam porttitor",
    Material: "CBN",
    Quantity: 48,
    PurchaseDate: "10/16/2018"
  },
  {
    id: 89,
    Description: "pede justo eu",
    Category: "Tools",
    SubCategory: "c clamps",
    Type: "ligula",
    Specification: "ante",
    Material: "Cermets",
    Quantity: 85,
    PurchaseDate: "9/10/2018"
  },
  {
    id: 90,
    Description: "at velit",
    Category: "measuring instrument",
    SubCategory: "compass",
    Type: "nec",
    Specification: "ante ipsum primis",
    Material: "Cermets",
    Quantity: 20,
    PurchaseDate: "1/7/2019"
  },
  {
    id: 91,
    Description: "vel accumsan tellus nisi",
    Category: "Fluids",
    SubCategory: "parallel blocks",
    Type: "convallis",
    Specification: "sem",
    Material: "Sialon",
    Quantity: 84,
    PurchaseDate: "11/27/2018"
  },
  {
    id: 92,
    Description: "amet cursus id",
    Category: "Tools",
    SubCategory: "oil stones",
    Type: "nec",
    Specification: "nisl",
    Material: "Cermets",
    Quantity: 15,
    PurchaseDate: "3/30/2019"
  },
  {
    id: 93,
    Description: "justo in hac habitasse",
    Category: "measuring instrument",
    SubCategory: "external tooth lock",
    Type: "lobortis",
    Specification: "ac lobortis vel",
    Material: "UCON",
    Quantity: 49,
    PurchaseDate: "5/1/2018"
  },
  {
    id: 94,
    Description: "ut",
    Category: "Fluids",
    SubCategory: "vices",
    Type: "mi",
    Specification: "nibh",
    Material: "Cermets",
    Quantity: 94,
    PurchaseDate: "9/28/2018"
  },
  {
    id: 95,
    Description: "ipsum integer",
    Category: "Fastners",
    SubCategory: "lubrication",
    Type: "odio",
    Specification: "massa id lobortis",
    Material: "UCON",
    Quantity: 8,
    PurchaseDate: "9/27/2018"
  },
  {
    id: 96,
    Description: "maecenas",
    Category: "Machines",
    SubCategory: "brushes",
    Type: "sodales",
    Specification: "nec",
    Material: "HCS",
    Quantity: 53,
    PurchaseDate: "3/8/2019"
  },
  {
    id: 97,
    Description: "justo pellentesque viverra",
    Category: "Fluids",
    SubCategory: "goggles",
    Type: "fermentum",
    Specification: "nulla",
    Material: "CBN",
    Quantity: 61,
    PurchaseDate: "4/27/2018"
  },
  {
    id: 98,
    Description: "porttitor lacus",
    Category: "measuring instrument",
    SubCategory: "Dustbins",
    Type: "pharetra",
    Specification: "eleifend luctus ultricies",
    Material: "Sialon",
    Quantity: 95,
    PurchaseDate: "10/3/2018"
  },
  {
    id: 99,
    Description: "interdum",
    Category: "Fluids",
    SubCategory: "spanners",
    Type: "urna",
    Specification: "in",
    Material: "UCON",
    Quantity: 71,
    PurchaseDate: "9/10/2018"
  },
  {
    id: 100,
    Description: "hac habitasse platea",
    Category: "Tools",
    SubCategory: "washers",
    Type: "in",
    Specification: "nam",
    Material: "Diamond",
    Quantity: 85,
    PurchaseDate: "3/28/2019"
  }
];

export default data;
